#!/usr/bin/env bash
# Copyright (c) Microsoft. All rights reserved.
# Note: Windows Bash doesn't support shebang extra params
set -e

APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
cd $APP_HOME

source "$APP_HOME/scripts/.functions.sh"

#Script Args
repo=both
tag="testing"
dockeraccount="azureiotpcs"

run_tests() {

    header2 "Now Running $repo tests"

    ./StorageAdapter/run.sh "Storage Adapter Tests" -t $tag -da $dockeraccount

    ./DeviceSimulation/run.sh "Device Simulation Tests" -t $tag -da $dockeraccount
}

while [[ $# -gt 0 ]] ;
do
    opt=$1;
    shift;	
    case $opt in
      -dt|--dockertag) tag=$1; shift;;
        -da|--docker-account) dockeraccount=$1; shift;; 
        *) shift;
    esac
done

echo "The repo name is: " $2

run_tests

set +e
